export const FETCH_PILOTS = 'FETCH_PILOTS';
export const RECEIVE_PILOTS = 'RECEIVE_PILOTS';
export const FETCH_FLIGHTS = 'FETCH_FLIGHTS';
export const RECEIVE_FLIGHTS = 'RECEIVE_FLIGHTS';
export const FETCH_FLIGHT_DATES = 'FETCH_FLIGHT_DATES';
export const RESET_FLIGHT_DATES = 'RESET_FLIGHT_DATES';
export const RECEIVE_FLIGHT_DATES = 'RECEIVE_FLIGHT_DATES';
export const FETCH_FLIGHTS_BY_DATE = 'FETCH_FLIGHTS_BY_DATE';
export const RECEIVE_FLIGHTS_BY_DATE = 'RECEIVE_FLIGHTS_BY_DATE';
export const FETCH_FLIGHTS_BY_PILOT = 'FETCH_FLIGHTS_BY_PILOT';
export const RECEIVE_FLIGHTS_BY_PILOT = 'RECEIVE_FLIGHTS_BY_PILOT';
export const FETCH_FLIGHTS_BY_DISTANCE = 'FETCH_FLIGHTS_BY_DISTANCE';
export const RECEIVE_FLIGHTS_BY_DISTANCE = 'RECEIVE_FLIGHTS_BY_DISTANCE';
export const RESET_FLIGHTS = 'RESET_FLIGHTS';

export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const HIDE_RASP_FORM = 'HIDE_RASP_FORM';
